In [21]:
import pandas as pd
import joblib 
from sklearn.inspection import permutation_importance
from sklearn.model_selection import train_test_split

# laod dataset
train_df = pd.read_csv(r"C:\Users\chill\OneDrive\Documents\ML-DS Competition\StudentHealthRisk\datasets\train.csv")
# laod trained model
model = joblib.load("results\lgbm.joblib")
print("train dataset and trained model load successfully")

train dataset and trained model load successfully

In [22]:
sample = train_df.iloc[:20,:].to_csv("results/sample.csv", index=False)

In [2]:
train_df.head(3)

,id,health_condition,sleep_duration,heart_rate,bmi,calorie_expenditure,step_count,exercise_duration,water_intake,diet_type,stress_level,sleep_quality,physical_activity_level,smoking_alcohol,gender
0,0,unhealthy,5.22,70.6,25.66,2174.0,1326.0,19.8,1.86,veg,high,average,sedentary,yes,female
1,1,at-risk,5.53,71.3,25.84,1966.0,9891.0,49.9,1.26,non-veg,low,average,moderate,yes,other
2,2,unhealthy,5.29,75.4,24.54,2688.0,14216.0,38.1,1.60,veg,high,poor,active,yes,male

In [3]:
train_df = train_df.iloc[:,1:]
y = train_df['health_condition']
X = train_df.drop("health_condition", axis=1)

In [4]:
y.tail(10)

690078        fit
690079    at-risk
690080    at-risk
690081    at-risk
690082    at-risk
690083    at-risk
690084    at-risk
690085        fit
690086    at-risk
690087    at-risk
Name: health_condition, dtype: object

In [5]:
X.columns

Index(['sleep_duration', 'heart_rate', 'bmi', 'calorie_expenditure',
       'step_count', 'exercise_duration', 'water_intake', 'diet_type',
       'stress_level', 'sleep_quality', 'physical_activity_level',
       'smoking_alcohol', 'gender'],
      dtype='object')

In [6]:
y = y.map({
    "fit":0,
    "unhealthy":1,
    "at-risk":2
})

y.tail(10)

690078    0
690079    2
690080    2
690081    2
690082    2
690083    2
690084    2
690085    0
690086    2
690087    2
Name: health_condition, dtype: int64

In [11]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.25, shuffle=True, random_state=42)

In [13]:
# Calculate Permutation Importance on the validation data
result = permutation_importance(
    model, X_test, y_test, n_repeats=10, random_state=42, scoring="accuracy"
)
importance_df = pd.DataFrame({
    "Feature": X_test.columns,
    "Importance_Mean": result.importances_mean,
    "Importance_Std": result.importances_std
}).sort_values(by="Importance_Mean", ascending=False)
print(importance_df)

c:\Users\chill\OneDrive\Documents\ML-DS Competition\comp\lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
c:\Users\chill\OneDrive\Documents\ML-DS Competition\comp\lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
c:\Users\chill\OneDrive\Documents\ML-DS Competition\comp\lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
c:\Users\chill\OneDrive\Documents\ML-DS Competition\comp\lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
c:\Users\chill\OneDrive\Documents\ML-DS Competition\comp\lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
c:\Users\chill\OneDrive\Documents\ML-DS Competition\comp\lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
c:\Users\chill\OneDrive\Documents\ML-DS Competition\comp\lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
c:\Users\chill\OneDrive\Documents\ML-DS Competition\comp\lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
c:\Users\chill\OneDrive\Documents\ML-DS Competition\comp\lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
c:\Users\chill\OneDrive\Documents\ML-DS Competition\comp\lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
c:\Users\chill\OneDrive\Documents\ML-DS Competition\comp\lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
c:\Users\chill\OneDrive\Documents\ML-DS Competition\comp\lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
c:\Users\chill\OneDrive\Documents\ML-DS Competition\comp\lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
c:\Users\chill\OneDrive\Documents\ML-DS Competition\comp\lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
c:\Users\chill\OneDrive\Documents\ML-DS Competition\comp\lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
c:\Users\chill\OneDrive\Documents\ML-DS Competition\comp\lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
c:\Users\chill\OneDrive\Documents\ML-DS Competition\comp\lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
c:\Users\chill\OneDrive\Documents\ML-DS Competition\comp\lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
c:\Users\chill\OneDrive\Documents\ML-DS Competition\comp\lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
c:\Users\chill\OneDrive\Documents\ML-DS Competition\comp\lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
c:\Users\chill\OneDrive\Documents\ML-DS Competition\comp\lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
c:\Users\chill\OneDrive\Documents\ML-DS Competition\comp\lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
c:\Users\chill\OneDrive\Documents\ML-DS Competition\comp\lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
c:\Users\chill\OneDrive\Documents\ML-DS Competition\comp\lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
c:\Users\chill\OneDrive\Documents\ML-DS Competition\comp\lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
c:\Users\chill\OneDrive\Documents\ML-DS Competition\comp\lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
c:\Users\chill\OneDrive\Documents\ML-DS Competition\comp\lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
c:\Users\chill\OneDrive\Documents\ML-DS Competition\comp\lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
c:\Users\chill\OneDrive\Documents\ML-DS Competition\comp\lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
c:\Users\chill\OneDrive\Documents\ML-DS Competition\comp\lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
c:\Users\chill\OneDrive\Documents\ML-DS Competition\comp\lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
c:\Users\chill\OneDrive\Documents\ML-DS Competition\comp\lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
c:\Users\chill\OneDrive\Documents\ML-DS Competition\comp\lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
c:\Users\chill\OneDrive\Documents\ML-DS Competition\comp\lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
c:\Users\chill\OneDrive\Documents\ML-DS Competition\comp\lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
c:\Users\chill\OneDrive\Documents\ML-DS Competition\comp\lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
c:\Users\chill\OneDrive\Documents\ML-DS Competition\comp\lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
c:\Users\chill\OneDrive\Documents\ML-DS Competition\comp\lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
c:\Users\chill\OneDrive\Documents\ML-DS Competition\comp\lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
c:\Users\chill\OneDrive\Documents\ML-DS Competition\comp\lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
c:\Users\chill\OneDrive\Documents\ML-DS Competition\comp\lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
c:\Users\chill\OneDrive\Documents\ML-DS Competition\comp\lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
c:\Users\chill\OneDrive\Documents\ML-DS Competition\comp\lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
c:\Users\chill\OneDrive\Documents\ML-DS Competition\comp\lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
c:\Users\chill\OneDrive\Documents\ML-DS Competition\comp\lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
c:\Users\chill\OneDrive\Documents\ML-DS Competition\comp\lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
c:\Users\chill\OneDrive\Documents\ML-DS Competition\comp\lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
c:\Users\chill\OneDrive\Documents\ML-DS Competition\comp\lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
c:\Users\chill\OneDrive\Documents\ML-DS Competition\comp\lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
c:\Users\chill\OneDrive\Documents\ML-DS Competition\comp\lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
c:\Users\chill\OneDrive\Documents\ML-DS Competition\comp\lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
c:\Users\chill\OneDrive\Documents\ML-DS Competition\comp\lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
c:\Users\chill\OneDrive\Documents\ML-DS Competition\comp\lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
c:\Users\chill\OneDrive\Documents\ML-DS Competition\comp\lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
c:\Users\chill\OneDrive\Documents\ML-DS Competition\comp\lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
c:\Users\chill\OneDrive\Documents\ML-DS Competition\comp\lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
c:\Users\chill\OneDrive\Documents\ML-DS Competition\comp\lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
c:\Users\chill\OneDrive\Documents\ML-DS Competition\comp\lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
c:\Users\chill\OneDrive\Documents\ML-DS Competition\comp\lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
c:\Users\chill\OneDrive\Documents\ML-DS Competition\comp\lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
c:\Users\chill\OneDrive\Documents\ML-DS Competition\comp\lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
c:\Users\chill\OneDrive\Documents\ML-DS Competition\comp\lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
c:\Users\chill\OneDrive\Documents\ML-DS Competition\comp\lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
c:\Users\chill\OneDrive\Documents\ML-DS Competition\comp\lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
c:\Users\chill\OneDrive\Documents\ML-DS Competition\comp\lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
c:\Users\chill\OneDrive\Documents\ML-DS Competition\comp\lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
c:\Users\chill\OneDrive\Documents\ML-DS Competition\comp\lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
c:\Users\chill\OneDrive\Documents\ML-DS Competition\comp\lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
c:\Users\chill\OneDrive\Documents\ML-DS Competition\comp\lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
c:\Users\chill\OneDrive\Documents\ML-DS Competition\comp\lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
c:\Users\chill\OneDrive\Documents\ML-DS Competition\comp\lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
c:\Users\chill\OneDrive\Documents\ML-DS Competition\comp\lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
c:\Users\chill\OneDrive\Documents\ML-DS Competition\comp\lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
c:\Users\chill\OneDrive\Documents\ML-DS Competition\comp\lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
c:\Users\chill\OneDrive\Documents\ML-DS Competition\comp\lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
c:\Users\chill\OneDrive\Documents\ML-DS Competition\comp\lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
c:\Users\chill\OneDrive\Documents\ML-DS Competition\comp\lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
c:\Users\chill\OneDrive\Documents\ML-DS Competition\comp\lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
c:\Users\chill\OneDrive\Documents\ML-DS Competition\comp\lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
c:\Users\chill\OneDrive\Documents\ML-DS Competition\comp\lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
c:\Users\chill\OneDrive\Documents\ML-DS Competition\comp\lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
c:\Users\chill\OneDrive\Documents\ML-DS Competition\comp\lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
c:\Users\chill\OneDrive\Documents\ML-DS Competition\comp\lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
c:\Users\chill\OneDrive\Documents\ML-DS Competition\comp\lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
c:\Users\chill\OneDrive\Documents\ML-DS Competition\comp\lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
c:\Users\chill\OneDrive\Documents\ML-DS Competition\comp\lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
c:\Users\chill\OneDrive\Documents\ML-DS Competition\comp\lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
c:\Users\chill\OneDrive\Documents\ML-DS Competition\comp\lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(

                    Feature  Importance_Mean  Importance_Std
0            sleep_duration         0.134097        0.000665
8              stress_level         0.085902        0.000575
10  physical_activity_level         0.044789        0.000428
2                       bmi         0.015314        0.000482
5         exercise_duration         0.004141        0.000189
4                step_count         0.002881        0.000200
11          smoking_alcohol         0.001801        0.000162
6              water_intake         0.000779        0.000184
1                heart_rate         0.000310        0.000148
7                 diet_type         0.000161        0.000146
12                   gender        -0.000015        0.000100
9             sleep_quality        -0.000144        0.000073
3       calorie_expenditure        -0.000835        0.000097

In [7]:
test_df = pd.read_csv(r"C:\Users\chill\OneDrive\Documents\ML-DS Competition\StudentHealthRisk\datasets\test.csv")
test_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 295753 entries, 0 to 295752
Data columns (total 14 columns):
 #   Column                   Non-Null Count   Dtype
---  ------                   --------------   -----
 0   id                       295753 non-null  int64
 1   sleep_duration           263182 non-null  float64
 2   heart_rate               292396 non-null  float64
 3   bmi                      289797 non-null  float64
 4   calorie_expenditure      273101 non-null  float64
 5   step_count               289789 non-null  float64
 6   exercise_duration        292795 non-null  float64
 7   water_intake             277120 non-null  float64
 8   diet_type                292795 non-null  object
 9   stress_level             260263 non-null  object
 10  sleep_quality            270754 non-null  object
 11  physical_activity_level  280058 non-null  object
 12  smoking_alcohol          283504 non-null  object
 13  gender                   286593 non-null  object
dtypes: float64(7), int64(1), object(6)
memory usage: 31.6+ MB

In [6]:
train_df.columns

Index(['health_condition', 'sleep_duration', 'heart_rate', 'bmi',
       'calorie_expenditure', 'step_count', 'exercise_duration',
       'water_intake', 'diet_type', 'stress_level', 'sleep_quality',
       'physical_activity_level', 'smoking_alcohol', 'gender'],
      dtype='object')

In [8]:
X.columns

Index(['sleep_duration', 'heart_rate', 'bmi', 'calorie_expenditure',
       'step_count', 'exercise_duration', 'water_intake', 'diet_type',
       'stress_level', 'sleep_quality', 'physical_activity_level',
       'smoking_alcohol', 'gender'],
      dtype='object')

In [9]:
# remove columns having negative importance mean
X = train_df.drop(['gender','sleep_quality','calorie_expenditure'], axis=1)
test_id = test_df["id"]
test_df = test_df.drop(["id","gender","sleep_quality","calorie_expenditure"], axis=1)
train_df.columns
test_df.columns

Index(['sleep_duration', 'heart_rate', 'bmi', 'step_count',
       'exercise_duration', 'water_intake', 'diet_type', 'stress_level',
       'physical_activity_level', 'smoking_alcohol'],
      dtype='object')

In [10]:
X.columns

Index(['health_condition', 'sleep_duration', 'heart_rate', 'bmi', 'step_count',
       'exercise_duration', 'water_intake', 'diet_type', 'stress_level',
       'physical_activity_level', 'smoking_alcohol'],
      dtype='object')

In [13]:
X = X.drop("health_condition", axis=1)
X.head(3)

,sleep_duration,heart_rate,bmi,step_count,exercise_duration,water_intake,diet_type,stress_level,physical_activity_level,smoking_alcohol
0,5.22,70.6,25.66,1326.0,19.8,1.86,veg,high,sedentary,yes
1,5.53,71.3,25.84,9891.0,49.9,1.26,non-veg,low,moderate,yes
2,5.29,75.4,24.54,14216.0,38.1,1.60,veg,high,active,yes

In [11]:
test_df.columns

Index(['sleep_duration', 'heart_rate', 'bmi', 'step_count',
       'exercise_duration', 'water_intake', 'diet_type', 'stress_level',
       'physical_activity_level', 'smoking_alcohol'],
      dtype='object')

In [14]:
ordinal_cols = ["stress_level", "physical_activity_level"]
categorical_cols = ["diet_type", "smoking_alcohol"]
numerical_cols = ['sleep_duration', 'heart_rate', 'bmi','step_count', 'exercise_duration', 'water_intake']

In [15]:
from sklearn.impute import SimpleImputer
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import OneHotEncoder, StandardScaler, OrdinalEncoder

cat_preprocessor = Pipeline(steps=[
    ("impute", SimpleImputer(strategy="most_frequent")),
    ("encode", OneHotEncoder(handle_unknown='ignore', sparse_output=False))
])

ord_preprocessor = Pipeline(steps=[
    ('impute', SimpleImputer(strategy="most_frequent")),
    ("encode", OrdinalEncoder())
])

num_preprocessor = Pipeline(steps=[
    ('impute', SimpleImputer(strategy="median")),
    ("scale", StandardScaler())    
])

preprocessor = ColumnTransformer(transformers=[
    ("cat", cat_preprocessor, categorical_cols),
    ("ord", ord_preprocessor, ordinal_cols),
    ("num", num_preprocessor, numerical_cols)
])

In [16]:
X.shape

(690088, 10)

In [17]:
test_df.shape

(295753, 10)

In [18]:
X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    random_state=42,
    test_size=0.22,
    shuffle=True
)
print(f"X train:{X_train.shape}\nX test: {X_test.shape}\ny train: {y_train.shape}\ny test: {y_test.shape}")

X train:(538268, 10)
X test: (151820, 10)
y train: (538268,)
y test: (151820,)

In [19]:
from lightgbm import LGBMClassifier
lgbm = Pipeline(steps=[
    ("prep", preprocessor),
    ("model", LGBMClassifier(
        learning_rate=0.05,
        max_depth=-1,
        min_child_samples=30,
        num_leaves=41
    ))
]) 

lgbm.fit(X_train, y_train)

[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.007316 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 1548
[LightGBM] [Info] Number of data points in the train set: 538268, number of used features: 14
[LightGBM] [Info] Start training from score -2.852951
[LightGBM] [Info] Start training from score -2.478832
[LightGBM] [Info] Start training from score -0.152586

Pipeline(steps=[('prep',
                 ColumnTransformer(transformers=[('cat',
                                                  Pipeline(steps=[('impute',
                                                                   SimpleImputer(strategy='most_frequent')),
                                                                  ('encode',
                                                                   OneHotEncoder(handle_unknown='ignore',
                                                                                 sparse_output=False))]),
                                                  ['diet_type',
                                                   'smoking_alcohol']),
                                                 ('ord',
                                                  Pipeline(steps=[('impute',
                                                                   SimpleImputer(strategy='most_frequent')),
                                                                  ('encode',
                                                                   OrdinalEncoder())]),
                                                  ['stress_level',
                                                   'physical_activity_level']),
                                                 ('num',
                                                  Pipeline(steps=[('impute',
                                                                   SimpleImputer(strategy='median')),
                                                                  ('scale',
                                                                   StandardScaler())]),
                                                  ['sleep_duration',
                                                   'heart_rate', 'bmi',
                                                   'step_count',
                                                   'exercise_duration',
                                                   'water_intake'])])),
                ('model',
                 LGBMClassifier(learning_rate=0.05, min_child_samples=30,
                                num_leaves=41))])

In [20]:
from sklearn.metrics import balanced_accuracy_score
y_pred = lgbm.predict(X_test)
accuracy = balanced_accuracy_score(y_test, y_pred)
print("accuracy: ", accuracy)

c:\Users\chill\OneDrive\Documents\ML-DS Competition\comp\lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(

accuracy:  0.8528970937205379